"""Provider-neutral evaluation contracts with offline and pinned production adapters."""

from aletheia_lab.model_gateway.contracts import (
    AdapterInvocationError,
    AttemptRecord,
    AttemptTiming,
    CancellationProbe,
    ClaimRelationProviderContext,
    Clock,
    GatewayContractError,
    GatewayExecutionResult,
    GatewayRequest,
    ParsedResponseArtifact,
    ProviderAdapter,
    ProviderBinding,
    ProviderCall,
    ProviderEnvelope,
    ProviderFailureCategory,
    RawResponseArtifact,
    RetryController,
    RuntimePolicyReference,
    UsageMetadata,
)
from aletheia_lab.model_gateway.fake import (
    DeterministicFakeAdapter,
    FakeFixture,
    FakeStep,
)
from aletheia_lab.model_gateway.openai import (
    OPENAI_API_BASE_URL,
    OPENAI_GATEWAY_ADAPTER_VERSION,
    OpenAIChatCompletionsGatewayAdapter,
    OpenAIGatewayConfigurationError,
    OpenAIGatewayPolicy,
)
from aletheia_lab.model_gateway.runtime import (
    execute_gateway_request,
    prepare_gateway_request,
    validate_response_payload,
    validate_response_schema,
)
from aletheia_lab.model_gateway.validation_v2 import (
    GloballyPacedProviderAdapter,
    OpenAIValidationV2Adapter,
    V2RetryController,
)

__all__ = [
    "AdapterInvocationError",
    "AttemptRecord",
    "AttemptTiming",
    "CancellationProbe",
    "ClaimRelationProviderContext",
    "Clock",
    "DeterministicFakeAdapter",
    "FakeFixture",
    "FakeStep",
    "GatewayContractError",
    "GatewayExecutionResult",
    "GatewayRequest",
    "GloballyPacedProviderAdapter",
    "OPENAI_API_BASE_URL",
    "OPENAI_GATEWAY_ADAPTER_VERSION",
    "OpenAIChatCompletionsGatewayAdapter",
    "OpenAIGatewayConfigurationError",
    "OpenAIGatewayPolicy",
    "OpenAIValidationV2Adapter",
    "ParsedResponseArtifact",
    "ProviderAdapter",
    "ProviderBinding",
    "ProviderCall",
    "ProviderEnvelope",
    "ProviderFailureCategory",
    "RawResponseArtifact",
    "RuntimePolicyReference",
    "RetryController",
    "UsageMetadata",
    "V2RetryController",
    "execute_gateway_request",
    "prepare_gateway_request",
    "validate_response_payload",
    "validate_response_schema",
]
