#!/usr/bin/env python3
"""Repo hygiene guard for Aletheia Lab.

Giữ cây thư mục repo (working/) CHUYÊN NGHIỆP và TÁCH BẠCH code với
tracking/planning. Script fail (exit 1) khi có file "lọt" vào repo mà lẽ ra phải
nằm ở folder tracking cá nhân/nhóm bên ngoài.

Cây thư mục repo nên gồm:
    src/  tests/  configs/  docs/ (chỉ spec kỹ thuật + adr)  scripts/
    data/**/.gitkeep  reports/  experiments/  examples/  notebooks/
    pyproject.toml  Makefile  LICENSE  README  CONTRIBUTING  CHANGELOG  .github/

KHÔNG chứa:
    - tracking/planning: roadmap, phase scorecard, risk register, decision/
      experiment log, master plan, paper plan, defense notes, project brief,
      implementation order, micro-task CSV, reuse map;
    - Office/binary: .docx/.doc/.pptx/.xlsx;
    - cache/junk: __pycache__, *.pyc, .DS_Store, .pytest_cache;
    - ngôn ngữ tự-chấm-điểm / dấu vết AI: "Danh vọng", "Score kỳ vọng",
      "paper potential", "defense readiness", "generated by AI", co-authored bot.

Severity:
    ERROR  (exit 1): office file, tracking file/dir, self-grade/AI content.
    WARN   (exit 0): junk đã bị .gitignore (DS_Store, __pycache__, empty dir).
             Dùng --strict để coi WARN là ERROR.

Nguồn quét:
    Mặc định: nếu là git repo -> chỉ quét file git đã track (đúng thứ sẽ push).
    Nếu chưa git init hoặc dùng --all -> quét toàn bộ filesystem.

Cách dùng:
    python scripts/check_repo_hygiene.py
    python scripts/check_repo_hygiene.py --root . --strict
    python scripts/check_repo_hygiene.py --all
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

JUNK_DIR_NAMES = {"__pycache__", ".pytest_cache", ".ruff_cache", ".mypy_cache",
                  ".ipynb_checkpoints"}
JUNK_FILE_NAMES = {".DS_Store", "Thumbs.db"}
JUNK_SUFFIXES = {".pyc", ".pyo"}
FORBIDDEN_SUFFIXES = {".docx", ".doc", ".pptx", ".ppt", ".xlsx", ".xls"}
FORBIDDEN_DIR_NAMES = {"tracking"}

TRACKING_NAME_PATTERNS = [
    r"master[_-]?plan", r"phase[_-]?tracking", r"phase[_-]?roadmap", r"roadmap",
    r"micro[_-]?task", r"scorecard", r"risk[_-]?register", r"decision[_-]?log",
    r"experiment[_-]?log", r"paper[_-]?plan", r"defense[_-]?notes",
    r"project[_-]?brief", r"implementation[_-]?order", r"reuse[_-]?map",
    r"do[_-]?an[_-]?tot[_-]?nghiep",
]
TRACKING_RE = re.compile("|".join(TRACKING_NAME_PATTERNS), re.IGNORECASE)

CONTENT_RED_FLAGS = [
    re.compile(r"danh\s*v[oọ]ng", re.IGNORECASE),
    re.compile(r"score\s*k[yỳ]\s*v[oọ]ng", re.IGNORECASE),
    re.compile(r"paper\s*potential", re.IGNORECASE),
    re.compile(r"defense\s*readiness", re.IGNORECASE),
    re.compile(r"generated\s+by\s+(ai|claude|gpt)\b", re.IGNORECASE),
    re.compile(r"co-authored-by:\s*(claude|assistant|gpt)", re.IGNORECASE),
]

SKIP_WALK_DIRS = {".git", ".venv", "venv", "node_modules"} | JUNK_DIR_NAMES
ALLOW_RELATIVE = {
    "scripts/check_repo_hygiene.py",
    "scripts/export_report_tables.py",
    "scripts/run_benchmark.py",
    "src/aletheia_lab/reporting/tables.py",
}


def git_tracked(root: Path) -> list[Path] | None:
    try:
        out = subprocess.run(["git", "-C", str(root), "ls-files"],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    files = [root / line for line in out.stdout.splitlines() if line.strip()]
    return files or None


def fs_paths(root: Path):
    for p in root.rglob("*"):
        if set(p.relative_to(root).parts) & SKIP_WALK_DIRS:
            continue
        yield p


def scan_content(p: Path) -> str | None:
    if p.suffix.lower() != ".md" or not p.is_file():
        return None
    try:
        text = p.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return None
    for rx in CONTENT_RED_FLAGS:
        if rx.search(text):
            return rx.pattern
    return None


def check(root: Path, use_git: bool):
    errors: list[str] = []
    warns: list[str] = []
    tracked = git_tracked(root) if use_git else None
    paths = tracked if tracked is not None else list(fs_paths(root))

    for p in paths:
        try:
            rel = p.relative_to(root).as_posix()
        except ValueError:
            continue
        name = p.name

        if p.is_dir():
            if name in JUNK_DIR_NAMES:
                warns.append(f"[JUNK DIR]      {rel}/")
            elif name in FORBIDDEN_DIR_NAMES:
                errors.append(f"[TRACKING DIR]  {rel}/  -> tracking phải nằm ngoài repo")
            elif not any(p.iterdir()):
                warns.append(f"[EMPTY DIR]     {rel}/  -> thêm .gitkeep hoặc xóa")
            continue

        if name in JUNK_FILE_NAMES or p.suffix in JUNK_SUFFIXES:
            warns.append(f"[JUNK FILE]     {rel}")
            continue
        if p.suffix.lower() in FORBIDDEN_SUFFIXES:
            errors.append(f"[OFFICE FILE]   {rel}  -> .docx/.pptx/.xlsx không thuộc code repo")
            continue
        if rel not in ALLOW_RELATIVE and "adr/" not in rel and TRACKING_RE.search(name):
            errors.append(f"[TRACKING FILE] {rel}  -> chuyển sang folder tracking ngoài repo")
            continue
        flag = scan_content(p)
        if flag:
            errors.append(f"[SELF-GRADE/AI] {rel}  -> khớp '{flag}'")

    return sorted(set(errors)), sorted(set(warns)), (tracked is not None)


def main() -> int:
    ap = argparse.ArgumentParser(description="Aletheia Lab repo hygiene guard")
    ap.add_argument("--root", default=".")
    ap.add_argument("--all", action="store_true", help="Quét toàn bộ filesystem (bỏ qua git)")
    ap.add_argument("--strict", action="store_true", help="Coi WARN là ERROR")
    args = ap.parse_args()

    root = Path(args.root).resolve()
    errors, warns, via_git = check(root, use_git=not args.all)
    src = "git-tracked files" if via_git else "filesystem"
    print(f"Hygiene scan ({src}) trên {root.name}/")

    for w in warns:
        print("  WARN  " + w)
    for e in errors:
        print("  ERROR " + e)

    blocking = errors + (warns if args.strict else [])
    if not blocking:
        msg = "PASS"
        if warns:
            msg += f" ({len(warns)} warning không chặn — junk đã bị .gitignore)"
        print(f"\nOK: repo hygiene {msg}.")
        return 0
    print(f"\nFAIL: {len(errors)} error"
          + (f", {len(warns)} warning (strict)" if args.strict else "")
          + ". Code ở repo, tracking/planning/docx ở folder tracking riêng.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
